name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: npm install
      - run: npm run lint
      - run: npm run build
      - run: npx gh-pages -d dist -u "GitHub Actions <bots@github.com>" -t -f -r https://zce:${{ secrets.GITHUB_TOKEN }}@github.com/zce/contents.git
